In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
# Declare a list
d = [34, 56, 90, 23, 41]

In [4]:
#command to convert the list into an array
data = np.array(d)

In [5]:
data

array([34, 56, 90, 23, 41])

In [6]:
d = [[1,6,3,4], [4,6,9,1], [5,6,9,0]]
data = np.array(d)

In [7]:
data

array([[1, 6, 3, 4],
       [4, 6, 9, 1],
       [5, 6, 9, 0]])

In [8]:
# Dimension of the array
data.ndim


2

In [9]:
# shape - rows and columns
data.shape

(3, 4)

In [10]:
# type of data
data.dtype

dtype('int64')

In [11]:
# Declaring arrays of zeros
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#matrix format 3 rows and 4 columns
data = np.zeros((3,4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
data = np.ones(10)
data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
data = np.ones((3,4))
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
data = data ** 2
data


array([[ 1,  4,  9],
       [16, 25, 36]])

In [18]:
data = data -1
data

array([[ 0,  3,  8],
       [15, 24, 35]])

In [19]:
data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[4,5,6],[1,2,3]])
data2 > data1

array([[ True,  True,  True],
       [False, False, False]])

In [20]:
data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[4,5,6],[1,2,3]])
data2 - data1

array([[ 3,  3,  3],
       [-3, -3, -3]])

In [21]:
data = np.arange(0,10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
data[6:9]

array([6, 7, 8])

In [23]:
data[6:9] = 50
data

array([ 0,  1,  2,  3,  4,  5, 50, 50, 50,  9])

In [24]:
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
data1 = data[6:9]
data1

array([50, 50, 50])

In [27]:
data1[1] = 25
data1

array([50, 25, 50])

In [28]:
data[:]=42
data

array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42])

In [86]:
#RANDOM NUMBERS
data = ((np.random.randn()))
data

-0.1542902572261522

In [70]:
data1 = ((np.random.rand()))
data1

0.15572582188274464

In [89]:
data = np.random.rand(2,3)
data

array([[0.22111593, 0.55530363, 0.18496595],
       [0.10455468, 0.13851151, 0.47969014]])

In [91]:
data = data * 10
data

array([[22.11159259, 55.53036341, 18.49659511],
       [10.45546789, 13.85115121, 47.96901372]])